### ISSUE TITLE
tools/epm command unavailable on Ubuntu 18.04

### ISSUE THREAD

**Issue by stephenrob** [eprints/eprints3.4#9]
After installing eprints 3.4 using the ubuntu package there is nothing available at `tools/epm` to install any packages from the bazaar with.

Has this been changed in 3.4 over 3.3?

**Comment by drn05r** [comment]
Yes, there is a change in file location but the functional has not changed in any significant change way.  tools/epm can now be found at /usr/share/eprints/ingredients/bazaar/tools/epm.

Please confirm this is present and works as expected and I will close the issue.

**Comment by drn05r** [comment]
It looks like the latest version of EPrninst 3.4 has some issues with the command line tools for the Bazaar.  I will investigate and get back to you.

**Comment by stephenrob** [comment]
`ingredients/bazaar/tools/epm` does exist but I had to make the following changes to get this to run.

### Making it executable
```
chmod +x epm
```

### Updating the epm file

```
use lib "$FindBin::Bin/../perl_lib";
```
To

```
use lib "$FindBin::Bin/../../../perl_lib";
```

### Further Error

I'm now getting the following error when trying to install a plugin but i suspect this is because we are trying to install them without a repository existing currently in our automation script.

```
Can't use an undefined value as an ARRAY reference at /usr/share/eprints/ingredients/bazaar/tools/../../../perl_lib/EPrints/Language.pm line 116.
```

**Comment by drn05r** [comment]
You look as though you are currently walking down the same path as me.

The latest issue you see is due to the default install not having a flavour defined.  I think that tools/epm must have got missed off of the integration testing, as these issues should have been fixed at the time the bazaar ingredient was created.

**Comment by stephenrob** [comment]
Following that error I installed the flavour for publications using the steps here https://wiki.eprints.org/w/Installing_EPrints_on_Debian/Ubuntu but still seeing the same error when running epm install without a repository existing.

**Comment by drn05r** [comment]
So there is one further step you need to potentially perform.  Have you already got an archive?  If so did you create it with "epadmin create" on this new 3.4 system you installed or was it copied from elsewhere (i.e. a 3.3 instance of EPrints)?  You need to make sure their is a file in your archive's **cfg/cfg.d/** (e.g. /usr/share/eprints/archives/test/cfg/cfg.d/) directory called **00_flavour.pl** with the following contents:

> $c->{flavour} = 'pub';

If you created the repository after you added the pub_lib flavour to the flavours directory then this file and its contents should be created automatically.  Also it should be noted that when you unpack the tarball from the Bazaar with the publication flavour you must only copy the pub_lib directory into /usr/share/eprints/flavours/.

**Comment by drn05r** [comment]
Also you need to make the following tweak to **bazaar/tools/epm** by replacing:

> my $repo = EPrints::Repository->new;

with

> my @_repoids = EPrints::Config::get_repository_ids();
> my $_repoid = scalar(@_repoids) ? $_repoids[0] : undef;
> my $repo = EPrints::Repository->new( $_repoid );

**Comment by stephenrob** [comment]
Thanks, I've updated the epm code to use that and it seems to be installing the plugins correctly at this time.

**Comment by drn05r** [comment]
OK.  Good to know.   I will commit the changes to fix this but it will be a while before it makes it into a release.
